/**
 * Script bổ sung memoryTip, context, related cho 460 từ còn thiếu
 */
const fs = require('fs');
const path = require('path');

const MEMORY_TIPS = {
  // ── Appearance (missing) ──
  'Young': 'Young → "dăng" → trẻ. Youngster = thanh niên',
  'Old': 'Old → "ôn-đ" → già. Old school = kiểu cũ',
  'Freckles': 'Freckle + s → những đốm tàn nhang trên da',
  'Pale': 'Pale → "pây-ồ" → nhợt nhạt, da trắng bệch',
  'Tan': 'Tan → "ten" → rám nắng. Suntan = cháy nắng',
  'Plump': 'Plump → "plăm-p" → mũm mĩm, tròn trịa (dễ thương hơn "fat")',

  // ── Personality (missing) ──
  'Clever': 'Clever → "clé-vơ" → thông minh, khéo léo',
  'Curious': 'Curious → Cure (chữa) + ious → tò mò muốn "chữa" mọi thắc mắc',
  'Rude': 'Rude → "rud" → thô lỗ. Rude = trái nghĩa Polite',
  'Cruel': 'Cruel → "cru-ồ" → tàn nhẫn. Cruelty = sự tàn ác',
  'Ambitious': 'Ambi (cả hai) + tious → muốn cả hai → tham vọng',
  'Loyal': 'Loyal → "loi-ồ" → trung thành. Royal (hoàng gia) cần Loyal',
  'Optimistic': 'Opti (optimal = tối ưu) + mistic → luôn nhìn tích cực',
  'Pessimistic': 'Pessi → "pé-xi" → bi quan. Trái nghĩa Optimistic',

  // ── Emotions (missing) ──
  'Ashamed': 'A + Shamed → cảm thấy xấu hổ',
  'Grateful': 'Grate + ful → đầy lòng biết ơn. "I\'m grateful" dùng rất nhiều',
  'Calm': 'Calm → "cam" → bình tĩnh. L im lặng → bình tĩnh không nói',
  'Anxious': 'Anxious → "eng-shớt" → lo âu. Anxiety = nỗi lo',
  'Content': 'Content → "cơn-ten" → hài lòng (cũng = nội dung)',

  // ── Family (missing) ──
  'Parent': 'Parent → Pa (bố) + rent → cha mẹ',
  'Child': 'Children (số nhiều) → trẻ em. Childhood = tuổi thơ',
  'Grandchild': 'Grand + Child → cháu (của ông bà)',
  'Neighbor': 'Neigh (hàng) + bor → hàng xóm. Neighbourhood = khu phố',
  'Colleague': 'Co (cùng) + league → cùng đội → đồng nghiệp',
  'Classmate': 'Class + Mate (bạn) → bạn cùng lớp',
  'Boyfriend': 'Boy + Friend → bạn trai',
  'Girlfriend': 'Girl + Friend → bạn gái',
  'Fiancé': 'Fiancé (nam) / Fiancée (nữ) → hôn phu/hôn thê (gốc Pháp)',
  'Widow': 'Widow → "ui-đâu" → góa phụ. Widower = đàn ông góa',
  'Orphan': 'Orphan → "o-phần" → trẻ mồ côi. Orphanage = trại mồ côi',

  // ── Actions/Daily ──
  'Born': 'Born → "bon" → được sinh ra. Birthday = ngày sinh',
  'Grow up': 'Grow (lớn) + Up (lên) → lớn lên, trưởng thành',
  'Teenager': 'Teen + ager → tuổi teen (13-19)',
  'Adult': 'Adult → "ơ-đớt" → người trưởng thành',
  'Elderly': 'Elder + ly → người cao tuổi (lịch sự hơn "old")',
  'Breathe': 'Breath (hơi thở) + e → thở. Breathe in = hít vào',
  'Sleep': 'Sleep → "x-líp" → ngủ. Sleepy = buồn ngủ',
  'Wake up': 'Wake (thức) + Up (dậy) → thức dậy. Alarm = báo thức',
  'Walk': 'Walk → "uóc" → đi bộ. Sidewalk = vỉa hè',
  'Run': 'Run → "rắn" → chạy. Runner = người chạy',
  'Sit': 'Sit → "xít" → ngồi. Sit down = ngồi xuống',
  'Stand': 'Stand → "x-ten-đ" → đứng. Stand up = đứng lên',
  'Speak': 'Speak → Speaker (loa/người nói). Speak up = nói to lên',
  'Listen': 'Listen → "lít-xần" → nghe. T im lặng. Listener = người nghe',
  'Think': 'Think → "think" → nghĩ. Thinker = nhà tư tưởng',
  'Laugh': 'Laugh → "láp" → cười. GH đọc là /f/. Laughter = tiếng cười',
  'Cry': 'Cry → "crai" → khóc. Cũng = kêu, hét (a cry for help)',
  'Smile': 'Smile → "x-mai-ồ" → mỉm cười 😊',
  'Wave': 'Wave → "uây-v" → vẫy tay. Cũng = sóng (ocean wave)',

  // ── Fruits ──
  'Apple': 'Apple → "é-pồ" → táo 🍎. Apple Inc = hãng táo',
  'Banana': 'Banana → "bơ-na-na" → chuối 🍌',
  'Orange': 'Orange → "o-rịn-ch" → cam 🍊. Cũng = màu cam',
  'Grape': 'Grape → "grây-p" → nho 🍇. Grapefruit = bưởi',
  'Mango': 'Mango → "meng-gô" → xoài 🥭',
  'Watermelon': 'Water (nước) + Melon (dưa) → dưa hấu 🍉 chứa nhiều nước',
  'Strawberry': 'Straw (rơm) + Berry (quả mọng) → dâu tây 🍓',
  'Pineapple': 'Pine (thông) + Apple (táo) → dứa/thơm, hình giống quả thông',
  'Peach': 'Peach → "pít-ch" → đào 🍑',
  'Lemon': 'Lemon → "le-mần" → chanh vàng 🍋',
  'Lime': 'Lime → "lai-m" → chanh xanh. Lime + Lemon = hai loại chanh',
  'Cherry': 'Cherry → "che-ri" → anh đào 🍒',
  'Coconut': 'Coco + Nut → quả dừa, nhìn như trái cây + hạt',
  'Avocado': 'Avocado → "a-vơ-ca-đô" → bơ. Guacamole = sốt bơ',
  'Papaya': 'Papaya → "pơ-pai-a" → đu đủ',
  'Durian': 'Durian → "đu-ri-ần" → sầu riêng. "Vua trái cây" Đông Nam Á',
  'Lychee': 'Lychee → "lai-chi" → vải (quả). Gốc tiếng Trung',
  'Dragon fruit': 'Dragon (rồng) + Fruit → thanh long, quả có hình rồng',
  'Pomelo': 'Pomelo → "po-me-lô" → bưởi. To hơn grapefruit',
  'Guava': 'Guava → "gua-va" → ổi 🍐',

  // ── Vegetables ──
  'Carrot': 'Carrot → "ke-rớt" → cà rốt 🥕. Thỏ thích ăn carrot',
  'Tomato': 'Tomato → "tơ-mây-tô" → cà chua 🍅',
  'Potato': 'Potato → "pơ-tây-tô" → khoai tây 🥔. Couch potato = lười biếng',
  'Onion': 'Onion → "ơ-niần" → hành tây 🧅. Cắt hành = khóc',
  'Garlic': 'Garlic → "ga-lịc" → tỏi 🧄. Garlic bread = bánh mì tỏi',
  'Cabbage': 'Cabbage → "ké-bịch" → bắp cải 🥬',
  'Lettuce': 'Lettuce → "lé-tịt" → rau diếp/xà lách',
  'Cucumber': 'Cucumber → "kiu-căm-bơ" → dưa leo 🥒. Cool as a cucumber = bình tĩnh',
  'Broccoli': 'Broccoli → "bro-cơ-li" → bông cải xanh 🥦',
  'Spinach': 'Spinach → "x-pi-nịch" → rau chân vịt. Popeye ăn spinach!',
  'Corn': 'Corn → "con" → bắp/ngô 🌽. Popcorn = bỏng ngô',
  'Pumpkin': 'Pumpkin → "păm-kin" → bí ngô 🎃. Halloween dùng pumpkin',
  'Mushroom': 'Mush + Room → nấm 🍄. Giống phòng mềm mại',
  'Bean': 'Bean → "bin" → đậu. Coffee bean = hạt cà phê',
  'Pea': 'Pea → "pi" → đậu hạt nhỏ. Green peas = đậu xanh',
  'Ginger': 'Ginger → "gin-chơ" → gừng. Ginger tea = trà gừng',
  'Celery': 'Celery → "xe-lơ-ri" → cần tây',
  'Eggplant': 'Egg (trứng) + Plant (cây) → cà tím, hình giống trứng',
  'Sweet potato': 'Sweet (ngọt) + Potato (khoai) → khoai lang',

  // ── Seafood/Meat (missing) ──
  'Lamb': 'Lamb → "lam" → thịt cừu non. B im lặng',
  'Crab': 'Crab → "cráp" → cua 🦀',
  'Squid': 'Squid → "x-quít" → mực ống 🦑',
  'Oyster': 'Oyster → "oi-x-tơ" → hàu. Oyster sauce = dầu hào',
  'Clam': 'Clam → "clam" → nghêu/ngao',
  'Lobster': 'Lobster → "lốp-x-tơ" → tôm hùm 🦞. Cao cấp!',
  'Salmon': 'Salmon → "xa-mần" → cá hồi. L im lặng!',
  'Tuna': 'Tuna → "tu-na" → cá ngừ',
  'Sausage': 'Sausage → "xo-xịch" → xúc xích',
  'Bacon': 'Bacon → "bây-cần" → thịt xông khói 🥓',
  'Ham': 'Ham → "ham" → giăm bông. Hamburger = Ham + burger',
  'Steak': 'Steak → "x-tây-k" → bít tết 🥩',
  'Wing': 'Wing → "uing" → cánh (gà). Chicken wings = cánh gà',
  'Rib': 'Rib → "ríp" → sườn. BBQ ribs = sườn nướng',

  // ── Cooking verbs ──
  'Cook': 'Cook → "cúc" → nấu ăn. Cooker = nồi cơm',
  'Boil': 'Boil → "boi-ồ" → luộc, đun sôi. Boiling water = nước sôi',
  'Fry': 'Fry → "phrai" → chiên/rán. French fries = khoai chiên',
  'Grill': 'Grill → "grin" → nướng (trên vỉ). BBQ grill',
  'Bake': 'Bake → "bây-k" → nướng (trong lò). Baker = thợ bánh',
  'Steam': 'Steam → "x-tim" → hấp. Steam cũng = hơi nước',
  'Roast': 'Roast → "rôs-t" → quay. Roast chicken = gà quay',
  'Stir': 'Stir → "x-tơ" → khuấy/xào. Stir-fry = xào',
  'Chop': 'Chop → "chóp" → chặt/thái. Chopstick = đũa (que chặt)',
  'Slice': 'Slice → "x-lai-x" → cắt lát mỏng. A slice of pizza',
  'Peel': 'Peel → "pin" → gọt vỏ. Banana peel = vỏ chuối',
  'Mix': 'Mix → "mích-x" → trộn. Mixer = máy trộn',

  // ── Sauces/Condiments ──
  'Soy sauce': 'Soy (đậu nành) + Sauce → nước tương/xì dầu',
  'Fish sauce': 'Fish (cá) + Sauce → nước mắm 🇻🇳',
  'Vinegar': 'Vine (nho) + gar → giấm, làm từ nho lên men',
  'Oil': 'Oil → "oi-ồ" → dầu ăn. Olive oil = dầu ô liu',
  'Spicy': 'Spicy → "x-pai-xi" → cay 🌶️. Spice = gia vị',
  'Recipe': 'Recipe → "re-xi-pi" → công thức nấu ăn',

  // ── Meals ──
  'Breakfast': 'Break (phá) + Fast (nhịn ăn) → phá nhịn = bữa sáng',
  'Lunch': 'Lunch → "lăn-ch" → bữa trưa',
  'Dinner': 'Dinner → "đin-nơ" → bữa tối. Dinner date = hẹn ăn tối',
  'Snack': 'Snack → "x-nắc" → bữa phụ/ăn vặt',
  'Sandwich': 'Sand + Witch → phù thủy trong cát → bánh kẹp (Earl of Sandwich)',
  'Pizza': 'Pizza → "pít-za" → pizza 🍕 (gốc Ý)',
  'Burger': 'Burger → "bơ-gơ" → bánh burger 🍔. Hamburger',
  'Dessert': 'Dessert (tráng miệng) có 2 chữ S → muốn ăn tráng miệng nhiều! Desert (sa mạc) chỉ 1 S',
  'Porridge': 'Porridge → "po-rịch" → cháo. Goldilocks and the porridge',
  'Appetizer': 'Appetite (sự thèm ăn) + izer → món khai vị',

  // ── Taste ──
  'Delicious': 'Delicious → "đi-lí-shớt" → ngon tuyệt! Deli = quán ăn ngon',
  'Sweet': 'Sweet → "x-uít" → ngọt 🍬. Sweetheart = người yêu',
  'Sour': 'Sour → "xao-ơ" → chua 🍋',
  'Salty': 'Salt + y → mặn. Don\'t be salty = đừng cay cú',
  'Bitter': 'Bitter → "bít-tơ" → đắng. Bitter chocolate = sô-cô-la đen',
  'Hot': 'Hot → "hót" → nóng/cay 🔥',
  'Mild': 'Mild → "mai-ồ-đ" → nhẹ, dịu. Mild flavor = vị nhẹ',
  'Fresh': 'Fresh → "phré-sh" → tươi. Fresh air = không khí trong lành',
  'Ripe': 'Ripe → "rai-p" → chín. Ripe fruit = trái chín',
  'Raw': 'Raw → "ro" → sống (chưa nấu). Raw fish = cá sống (sushi)',
  'Crispy': 'Crispy → "crít-pi" → giòn. Crispy chicken = gà giòn',
  'Soft': 'Soft → "xóp-t" → mềm. Software = phần mềm (máy tính)',
  'Chewy': 'Chew (nhai) + y → dai, cần nhai nhiều',
  'Creamy': 'Cream + y → béo/kem. Creamy soup = súp kem',
  'Crunchy': 'Crunch + y → giòn tan. Crunchy chips = snack giòn',
  'Tasty': 'Taste (vị) + y → ngon, đậm vị',
  'Bland': 'Bland → "blanc-đ" → nhạt, vô vị',
  'Greasy': 'Grease (dầu mỡ) + y → nhiều dầu mỡ',
  'Savory': 'Savory → "xây-vơ-ri" → mặn mà, ngon miệng (≠ sweet)',
  'Stale': 'Stale → "x-tây-ồ" → ôi thiu, hết tươi. Stale bread',
  'Yummy': 'Yummy → "yăm-mi" → ngon (trẻ em hay dùng)',

  // ── Drinks (missing) ──
  'Hot chocolate': 'Hot (nóng) + Chocolate → sô-cô-la nóng ☕',
  'Herbal tea': 'Herb (thảo mộc) + al + Tea → trà thảo mộc 🌿',
  'Green tea': 'Green (xanh) + Tea → trà xanh 🍵',
  'Black tea': 'Black (đen) + Tea → trà đen/hồng trà',
  'Espresso': 'Espresso → "ét-prét-xô" → cà phê đậm đặc (gốc Ý)',
  'Latte': 'Latte → "la-tê" → cà phê sữa. Latte = sữa (tiếng Ý)',
  'Cappuccino': 'Cappuccino → "ca-pu-chi-nô" → cà phê bọt sữa ☕',
  'Americano': 'Americano → American + o → kiểu Mỹ (espresso + nước)',
  'Ginger tea': 'Ginger (gừng) + Tea → trà gừng ấm bụng',
  'Milk tea': 'Milk (sữa) + Tea → trà sữa 🧋. Rất phổ biến ở VN!',
  'Mocha': 'Mocha → "mô-ka" → cà phê + sô-cô-la',
  'Brew': 'Brew → "bru" → pha (trà/cà phê/bia). Brewery = nhà máy bia',
  'Steep': 'Steep → "x-tip" → ngâm/ủ (trà). Steep tea for 5 minutes',
  'Ice': 'Ice → "ai-x" → đá. Iced coffee = cà phê đá. Ice cream = kem',
  'Lemonade': 'Lemon + ade → nước chanh 🍋',
  'Smoothie': 'Smooth (mịn) + ie → sinh tố xay mịn',
  'Milkshake': 'Milk (sữa) + Shake (lắc) → sữa lắc',
  'Sparkling water': 'Spark (tia lửa) + ling → nước có ga, sủi tăm',
  'Iced tea': 'Ice + d + Tea → trà đá',
  'Iced coffee': 'Ice + d + Coffee → cà phê đá',
  'Coconut water': 'Coconut (dừa) + Water → nước dừa tươi 🥥',
  'Sugarcane juice': 'Sugarcane (mía) + Juice → nước mía 🇻🇳',
  'Mineral water': 'Mineral (khoáng) + Water → nước khoáng',
  'Straw': 'Straw → "x-tro" → ống hút. Cũng = rơm rạ',
  'Refreshing': 'Re (lại) + Fresh + ing → làm tươi mát lại',
  'Yogurt': 'Yogurt → "dô-gớt" → sữa chua',
  'Soy milk': 'Soy (đậu nành) + Milk → sữa đậu nành',
  'Almond milk': 'Almond (hạnh nhân) + Milk → sữa hạnh nhân',
  'Condensed milk': 'Condensed (cô đặc) + Milk → sữa đặc',
  'Cream': 'Cream → "crim" → kem. Ice cream = kem lạnh',
  'Whipped cream': 'Whip (đánh) + ped + Cream → kem tươi đánh bông',
  'Chocolate milk': 'Chocolate + Milk → sữa sô-cô-la',
  'Oat milk': 'Oat (yến mạch) + Milk → sữa yến mạch',
  'Buttermilk': 'Butter (bơ) + Milk → sữa bơ (lên men)',
  'Drink': 'Drink → "đrin-k" → uống. Drink/Drank/Drunk (bất quy tắc)',
  'Sip': 'Sip → "xíp" → nhấp/nhâm nhi. Take a sip = nhấp một ngụm',
  'Gulp': 'Gulp → "gớp" → nuốt ừng ực. Gulp it down!',
  'Pour': 'Pour → "po" → rót. Pour water = rót nước',
  'Fill': 'Fill → "phin" → đổ đầy. Fill up = đổ đầy',
  'Swallow': 'Swallow → "x-oua-lô" → nuốt. Cũng = chim én',
  'Thirsty': 'Thirst + y → khát nước. I\'m thirsty = tôi khát',
  'Toast': 'Toast → "tôs-t" → nâng cốc chúc. Cũng = bánh mì nướng 🍞',
  'Cup': 'Cup → "cắp" → tách. A cup of coffee ☕',
  'Glass': 'Glass → "glát" → cốc/ly. Cũng = kính/thủy tinh',
  'Bottle': 'Bottle → "bót-tồ" → chai. Water bottle = bình nước',
  'Mug': 'Mug → "mắc" → cốc lớn có tay cầm (café, trà)',
  'Teapot': 'Tea (trà) + Pot (bình) → ấm trà',
  'Pitcher': 'Pitcher → "pít-chơ" → bình rót nước lớn',
  'Beverage': 'Beverage → "bé-vơ-rịch" → đồ uống (formal hơn "drink")',

  // ── House (missing) ──
  'Living room': 'Living (sống) + Room → phòng sinh hoạt = phòng khách',
  'Dining room': 'Dining (ăn) + Room → phòng ăn',
  'Basement': 'Base (đáy) + ment → tầng hầm',
  'Attic': 'Attic → "é-tíc" → gác xép/tầng áp mái',
  'Balcony': 'Balcony → "ban-cơ-ni" → ban công',
  'Hallway': 'Hall + Way → hành lang',
  'Laundry room': 'Laundry (giặt) + Room → phòng giặt',
  'Staircase': 'Stair (bậc) + Case → cầu thang',
  'Yard': 'Yard → "da" → sân. Backyard = sân sau',
  'Sofa': 'Sofa → "xô-pha" → ghế sofa (từ mượn)',
  'Wardrobe': 'War + drobe → tủ quần áo. Narnia\'s wardrobe!',
  'Desk': 'Desk → "đét-k" → bàn làm việc',
  'Shelf': 'Shelf → "seo-f" → kệ. Shelves = số nhiều',
  'Drawer': 'Draw + er → ngăn kéo (kéo ra)',
  'Curtain': 'Curtain → "cơ-tần" → rèm cửa',
  'Carpet': 'Carpet → "ca-pít" → thảm trải sàn',
  'Pillow': 'Pillow → "pi-lô" → gối. Pillow fight = đánh gối',
  'Blanket': 'Blanket → "blen-kít" → chăn/mền',
  'Refrigerator': 'Re + fridge → tủ lạnh. Viết tắt: fridge',
  'Oven': 'Oven → "ơ-vần" → lò nướng',
  'Microwave': 'Micro (nhỏ) + Wave (sóng) → lò vi sóng',
  'Washing machine': 'Wash (giặt) + ing + Machine → máy giặt',
  'Air conditioner': 'Air (không khí) + Condition (điều kiện) + er → máy lạnh',
  'Fan': 'Fan → "phen" → quạt. Fan cũng = người hâm mộ',
  'Television': 'Tele (xa) + Vision (nhìn) → xem từ xa = TV 📺',
  'Vacuum cleaner': 'Vacuum (chân không) + Clean + er → máy hút bụi',
  'Iron': 'Iron → "ai-ần" → bàn ủi. Cũng = sắt. Iron Man!',
  'Kettle': 'Kettle → "ké-tồ" → ấm đun nước',
  'Toaster': 'Toast + er → máy nướng bánh mì',
  'Blender': 'Blend (trộn) + er → máy xay sinh tố',

  // ── Housework ──
  'Sweep': 'Sweep → "x-uíp" → quét nhà. Broom = chổi',
  'Mop': 'Mop → "móp" → lau nhà. Cũng = cây lau nhà',
  'Wash': 'Wash → "uósh" → rửa/giặt. Wash dishes = rửa chén',
  'Clean': 'Clean → "clin" → dọn dẹp/sạch sẽ',
  'Dust': 'Dust → "đớt" → phủi bụi. Dusty = bụi bặm',
  'Fold': 'Fold → "phôn-đ" → gấp (quần áo). Unfold = mở ra',
  'Tidy': 'Tidy → "tai-đi" → dọn gọn gàng. Tidy up!',
  'Fix': 'Fix → "phíc-x" → sửa chữa. Fixed = cố định',

  // ── Transportation (missing) ──
  'Scooter': 'Scooter → "x-cú-tơ" → xe tay ga/scooter',
  'Ambulance': 'Ambulance → "am-biu-lần-x" → xe cứu thương 🚑',
  'Fire truck': 'Fire (lửa) + Truck → xe cứu hỏa 🚒',
  'Road': 'Road → "rôu-đ" → đường. Roadmap = lộ trình',
  'Street': 'Street → "x-trít" → phố/đường phố. Wall Street',
  'Highway': 'High + Way → đường cao tốc',
  'Bridge': 'Bridge → "brít-ch" → cầu. Brooklyn Bridge',
  'Intersection': 'Inter (giữa) + Section (đoạn) → ngã tư, giao lộ',
  'Sidewalk': 'Side (bên) + Walk (đi) → vỉa hè',
  'Traffic light': 'Traffic (giao thông) + Light (đèn) → đèn giao thông 🚦',
  'Parking lot': 'Park (đỗ) + ing + Lot (bãi) → bãi đỗ xe',
  'Crosswalk': 'Cross (băng qua) + Walk → vạch sang đường',
  'Speed limit': 'Speed (tốc độ) + Limit (giới hạn) → giới hạn tốc độ',
  'Traffic jam': 'Traffic + Jam (mứt/kẹt) → kẹt xe, tắc đường',
  'Roundabout': 'Round (tròn) + About → vòng xuyến',
  'Drive': 'Drive → "đrai-v" → lái xe. Driver = tài xế',
  'Ride': 'Ride → "rai-đ" → cưỡi/đi (xe). Enjoy the ride!',
  'Fly': 'Fly → "phlai" → bay. Fly/Flew/Flown',
  'Sail': 'Sail → "xây-ồ" → đi thuyền buồm. Sailor = thủy thủ',
  'Depart': 'De + Part → rời đi. Departure = khởi hành',
  'Arrive': 'Arrive → "ơ-rai-v" → đến nơi. Arrival = sự đến',
  'Board': 'Board → "bo-đ" → lên (tàu/máy bay). Boarding pass',
  'Commute': 'Commute → "cơ-miut" → đi làm hàng ngày',
  'Navigate': 'Navi + gate → dẫn đường. Navigator = GPS',
  'Passenger': 'Pass + enger → hành khách. Passengers on board',
  'Ticket': 'Ticket → "tí-kít" → vé. Bus ticket = vé xe buýt',

  // ── Love (missing) ──
  'Crush': 'Crush → "crớsh" → thầm thương. Have a crush on = thích thầm',
  'Affection': 'Affect (ảnh hưởng) + ion → tình cảm, sự yêu mến',
  'Passion': 'Passion → "pa-shần" → đam mê, nhiệt huyết ❤️‍🔥',
  'Miss': 'Miss → "mít" → nhớ. I miss you = anh nhớ em',
  'Adore': 'Adore → "ơ-đo" → ngưỡng mộ, yêu quý',
  'Cherish': 'Cherish → "che-rish" → nâng niu, trân trọng',
  'Heartbreak': 'Heart (tim) + Break (vỡ) → đau khổ, tan vỡ 💔',
  'Faithful': 'Faith (niềm tin) + ful → chung thủy',
  'Devoted': 'Devote (cống hiến) + d → tận tụy, hết lòng',
  'Partner': 'Part + ner → đối tác/bạn đời',
  'Spouse': 'Spouse → "x-pao-z" → vợ/chồng (dùng chung)',
  'Soulmate': 'Soul (linh hồn) + Mate (bạn) → tri kỷ, nửa kia',
  'Ex': 'Ex → "ét-x" → người yêu cũ. Ex-boyfriend/ex-girlfriend',
  'Propose': 'Pro + pose → đề xuất/cầu hôn 💍. "Will you marry me?"',
  'Honeymoon': 'Honey (mật) + Moon (trăng) → tuần trăng mật 🌙',
  'Anniversary': 'Anni (mỗi năm) + versary → kỷ niệm hàng năm',
  'Engagement': 'Engage + ment → đính hôn. Engagement ring = nhẫn đính hôn',
  'Vow': 'Vow → "vao" → lời thề. Wedding vows = lời thề cưới',
  'Gift': 'Gift → "gift" → quà tặng 🎁. Gifted = tài năng',
  'Bouquet': 'Bouquet → "bu-kê" → bó hoa 💐 (gốc Pháp)',

  // ── Numbers (missing) ──
  'Four': 'Four → "pho" → số 4. Fourteen = 14',
  'Five': 'Five → "phai-v" → số 5. High five = đập tay! ✋',
  'Twenty': 'Twen + ty → 20. Twenty = 2 chục',
  'Fifty': 'Fif + ty → 50',
  'Billion': 'Billion → "bi-li-ần" → tỷ (1,000,000,000)',
  'Dozen': 'Dozen → "đa-zần" → tá (12)',
  'Pair': 'Pair → "pe" → cặp/đôi. A pair of shoes = đôi giày',
  'Fourth': 'Four + th → thứ tư (fourth floor = tầng 4)',
  'Fifth': 'Five → Fifth (thứ năm). Five thay ve→f, thêm th',
  'Tenth': 'Ten + th → thứ mười',
  'Last': 'Last → "lát" → cuối cùng. At last = cuối cùng',
  'Next': 'Next → "nét" → tiếp theo. Next time = lần sau',
  'Previous': 'Pre (trước) + vious → trước đó',
  'Half': 'Half → "hap" → một nửa. L im lặng!',
  'Quarter': 'Quarter → "quó-tơ" → một phần tư. 15 phút',
  'Double': 'Double → "đắp-bồ" → gấp đôi',
  'Triple': 'Triple → "trí-pồ" → gấp ba',
  'Add': 'Add → "ét" → cộng. Addition = phép cộng',
  'Subtract': 'Sub (dưới) + tract → trừ',
  'Multiply': 'Multi (nhiều) + ply → nhân',
  'Divide': 'Divide → "đi-vai-đ" → chia. Division = phép chia',
  'Equal': 'Equal → "í-quồ" → bằng. Equality = sự bình đẳng',
  'Total': 'Total → "tô-tồ" → tổng cộng',
  'Average': 'Average → "é-vơ-rịch" → trung bình',
  'Percent': 'Per (mỗi) + Cent (trăm) → phần trăm %',
  'Meter': 'Meter → "mí-tơ" → mét (đơn vị đo)',
  'Kilogram': 'Kilo (ngàn) + Gram → kg = kilogram',
  'Temperature': 'Temper (nhiệt) + ature → nhiệt độ 🌡️',
  'Distance': 'Dis + tance → khoảng cách. Long distance = đường dài',

  // ── Sports (missing) ──
  'Gymnastics': 'Gym + nastics → thể dục dụng cụ',
  'Golf': 'Golf → "gôn" → đánh golf ⛳',
  'Martial arts': 'Martial (quân sự) + Arts → võ thuật 🥋',
  'Hiking': 'Hike + ing → đi bộ đường dài/leo núi 🥾',
  'Surfing': 'Surf + ing → lướt sóng 🏄. Web surfing = lướt web',
  'Score': 'Score → "x-co" → điểm số. High score = điểm cao',
  'Win': 'Win → "uin" → thắng. Winner = người thắng 🏆',
  'Lose': 'Lose → "lu-z" → thua. Loser = người thua',
  'Kick': 'Kick → "kíc" → đá. Kick-off = bắt đầu',
  'Throw': 'Throw → "thrô" → ném. Throw/Threw/Thrown',
  'Catch': 'Catch → "két-ch" → bắt. Catch the ball!',
  'Hit': 'Hit → "hít" → đánh/đập. Hit/Hit/Hit (không đổi)',
  'Jump': 'Jump → "giăm-p" → nhảy. High jump = nhảy cao',
  'Sprint': 'Sprint → "x-print" → chạy nước rút',
  'Ball': 'Ball → "bon" → quả bóng ⚽🏀🎾',
  'Helmet': 'Helmet → "hen-mít" → mũ bảo hiểm ⛑️',
  'Medal': 'Medal → "mé-đồ" → huy chương 🏅. Gold medal',
  'Coach': 'Coach → "côu-ch" → huấn luyện viên',
  'Referee': 'Referee → "re-phơ-ri" → trọng tài',
  'Stadium': 'Stadium → "x-tây-đi-ầm" → sân vận động 🏟️',

  // ── Holidays (missing) ──
  'Independence Day': 'Independence (độc lập) + Day → Quốc khánh',
  'Lunar New Year': 'Lunar (mặt trăng) + New Year → Tết Nguyên Đán 🧧',
  'Mid-Autumn': 'Mid (giữa) + Autumn (mùa thu) → Tết Trung thu 🥮',
  'Holiday': 'Holy (thiêng liêng) + Day → ngày lễ/nghỉ',
  'Festival': 'Fest (lễ hội) + ival → lễ hội. Music festival',
  'Celebrate': 'Celeb + rate → ăn mừng 🎉. Celebrity = người nổi tiếng',
  'Decorate': 'Decor (trang trí) + ate → trang hoàng',
  'Fireworks': 'Fire (lửa) + Works → pháo hoa 🎆',
  'Costume': 'Costume → "cót-tium" → trang phục hóa trang 🎭',
  'Parade': 'Parade → "pơ-rây-đ" → diễu hành',
  'Card': 'Card → "cát" → thiệp. Christmas card = thiệp Noel',
  'Candle': 'Candle → "ken-đồ" → nến 🕯️',
  'Feast': 'Feast → "phít" → bữa tiệc lớn',
  'Tradition': 'Tradition → "trơ-đi-shần" → truyền thống',
  'Wish': 'Wish → "uish" → điều ước. Make a wish! ⭐',
  'Surprise': 'Sur + prise → bất ngờ! Surprise party 🎊',
  'Present': 'Present → quà (cũng = hiện tại). "Live in the present"',
  'Balloon': 'Balloon → "bơ-lun" → bóng bay 🎈',
  'Confetti': 'Confetti → "cơn-phé-ti" → hoa giấy (gốc Ý)',

  // ── Animals (missing) ──
  'Hamster': 'Hamster → "ham-x-tơ" → chuột hamster 🐹',
  'Goldfish': 'Gold (vàng) + Fish → cá vàng',
  'Parrot': 'Parrot → "pa-rớt" → con vẹt 🦜. Hay nói theo',
  'Goat': 'Goat → "gôu-t" → dê 🐐. GOAT = Greatest Of All Time',
  'Turtle': 'Turtle → "tơ-tồ" → rùa 🐢. Ninja Turtles!',
  'Wolf': 'Wolf → "úp" → sói 🐺. Wolves = số nhiều',
  'Fox': 'Fox → "phóc-x" → cáo 🦊. Foxy = xảo quyệt',
  'Deer': 'Deer → "đia" → hươu/nai 🦌. Dear (thân mến) ≠ Deer',
  'Giraffe': 'Giraffe → "gi-ráp" → hươu cao cổ 🦒. Con cao nhất!',
  'Zebra': 'Zebra → "zí-brơ" → ngựa vằn 🦓. Zebra crossing = vạch trắng',
  'Panda': 'Panda → "pen-đa" → gấu trúc 🐼. Kung Fu Panda',
  'Crocodile': 'Croco + dile → cá sấu 🐊',
  'Eagle': 'Eagle → "í-gồ" → đại bàng 🦅. Bald Eagle = biểu tượng Mỹ',
  'Penguin': 'Penguin → "pen-guin" → chim cánh cụt 🐧',
  'Shark': 'Shark → "shác" → cá mập 🦈. Baby shark doo doo!',
  'Whale': 'Whale → "uây-ồ" → cá voi 🐋. Blue whale = lớn nhất',
  'Dolphin': 'Dolphin → "đo-phin" → cá heo 🐬',
  'Octopus': 'Octo (8) + pus → bạch tuộc 🐙 có 8 xúc tu',
  'Jellyfish': 'Jelly (thạch) + Fish → sứa (mềm như thạch)',
  'Starfish': 'Star (sao) + Fish → sao biển ⭐🐟',
  'Bee': 'Bee → "bi" → ong 🐝. Busy as a bee = bận rộn',
  'Spider': 'Spider → "x-pai-đơ" → nhện 🕷️. Spider-Man!',
  'Mosquito': 'Mosqui + to → muỗi 🦟. Mosquito net = mùng',
  'Ladybug': 'Lady (quý bà) + Bug → bọ rùa 🐞. May mắn!',

  // ── Weather/Nature (missing) ──
  'Sunny': 'Sun + ny → nắng ☀️. Today is sunny = hôm nay nắng',
  'Rainy': 'Rain + y → mưa 🌧️. Rainy season = mùa mưa',
  'Cloudy': 'Cloud + y → nhiều mây ☁️',
  'Windy': 'Wind + y → nhiều gió 💨',
  'Snowy': 'Snow + y → có tuyết ❄️',
  'Stormy': 'Storm + y → có bão ⛈️',
  'Foggy': 'Fog + gy → có sương mù 🌫️',
  'Thunder': 'Thunder → "thăn-đơ" → sấm ⚡. Thor = thần sấm',
  'Lightning': 'Light (ánh sáng) + ning → tia chớp ⚡',
  'Rainbow': 'Rain (mưa) + Bow (cung) → cầu vồng 🌈',
  'Flood': 'Flood → "phlớt" → lũ lụt',
  'Drought': 'Drought → "drau-t" → hạn hán. GHT đọc /t/',
  'Breeze': 'Breeze → "brít" → gió nhẹ',
  'Humid': 'Humid → "hiu-mít" → ẩm. Humidity = độ ẩm',
  'Cave': 'Cave → "kây-v" → hang động. Caveman = người hang',
  'Valley': 'Valley → "va-li" → thung lũng. Silicon Valley',
  'Hill': 'Hill → "hin" → đồi. Uphill = lên dốc',
  'Volcano': 'Volcano → "von-kây-nô" → núi lửa 🌋',
  'Cliff': 'Cliff → "clíp" → vách đá',
  'Leaf': 'Leaf → "líp" → lá 🍃. Leaves = số nhiều',
  'Root': 'Root → "rut" → rễ cây. Root cause = nguyên nhân gốc',
  'Branch': 'Branch → "bren-ch" → cành cây. Chi nhánh (ngân hàng)',
  'Seed': 'Seed → "xít" → hạt giống',
  'Rose': 'Rose → "rôu-z" → hoa hồng 🌹. Roses are red...',
  'Sunflower': 'Sun (mặt trời) + Flower → hoa hướng dương 🌻',
  'Bamboo': 'Bamboo → "bam-bu" → tre 🎋. Bamboo forest',
  'Cactus': 'Cactus → "két-tớt" → xương rồng 🌵',

  // ── Public places (missing) ──
  'Police station': 'Police + Station → đồn cảnh sát 🚔',
  'Fire station': 'Fire + Station → trạm cứu hỏa 🚒',
  'Temple': 'Temple → "tem-pồ" → đền/chùa 🛕',
  'Government': 'Govern (cai trị) + ment → chính phủ 🏛️',
  'Embassy': 'Embassy → "em-bơ-xi" → đại sứ quán',
  'Court': 'Court → "cot" → tòa án. Basketball court = sân bóng rổ',
  'Supermarket': 'Super (siêu) + Market (chợ) → siêu thị 🛒',
  'Café': 'Café → "ca-phê" → quán cà phê ☕',
  'Bakery': 'Bake + ry → tiệm bánh 🍞',
  'Bookstore': 'Book (sách) + Store (cửa hàng) → nhà sách 📚',
  'Mall': 'Mall → "mon" → trung tâm thương mại 🏬',
  'Gas station': 'Gas + Station → trạm xăng ⛽',
  'Barbershop': 'Barber (thợ cắt) + Shop → tiệm cắt tóc 💈',
  'Laundromat': 'Laundro (giặt) + mat → tiệm giặt ủi',
  'Theater': 'Theater → "thí-ơ-tơ" → nhà hát/rạp 🎭',
  'Zoo': 'Zoo → "zu" → sở thú 🦁. Zoology = động vật học',
  'Amusement park': 'Amuse (giải trí) + ment + Park → công viên giải trí 🎢',
  'Gym': 'Gym → "gim" → phòng tập 🏋️. Gymnasium (đầy đủ)',
  'Playground': 'Play (chơi) + Ground (mặt đất) → sân chơi',
  'Swimming pool': 'Swimming + Pool → hồ bơi 🏊',
  'Harbor': 'Harbor → "ha-bơ" → cảng. Pearl Harbor',
  'Bus stop': 'Bus + Stop → trạm xe buýt 🚏',

  // ── Countries/Languages (missing) ──
  'India': 'India → "In-đi-a" → Ấn Độ 🇮🇳',
  'Singapore': 'Singapore → "Xing-ga-po" → Singapore 🇸🇬. Singa = sư tử',
  'Philippines': 'Philippines → "Phi-líp-pin" → Philippines 🇵🇭',
  'Malaysia': 'Malaysia → "Ma-lay-xi-a" → Malaysia 🇲🇾',
  'Indonesia': 'Indonesia → "In-đô-nê-xi-a" → Indonesia 🇮🇩',
  'Cambodia': 'Cambodia → "Cam-bô-đi-a" → Campuchia 🇰🇭',
  'Myanmar': 'Myanmar → "Mi-an-ma" → Myanmar (Burma) 🇲🇲',
  'Germany': 'Germany → "Giơ-mơ-ni" → Đức 🇩🇪. Deutsch',
  'Italy': 'Italy → "Ý-tơ-li" → Ý 🇮🇹. Pizza + Pasta',
  'Spain': 'Spain → "X-pây-n" → Tây Ban Nha 🇪🇸',
  'Russia': 'Russia → "Ra-shơ" → Nga 🇷🇺',
  'Canada': 'Canada → "Ca-na-đa" → Canada 🇨🇦. Maple leaf 🍁',
  'Brazil': 'Brazil → "Brơ-zin" → Brazil 🇧🇷. Bóng đá + Carnival',
  'Mexico': 'Mexico → "Méc-xi-cô" → Mexico 🇲🇽',
  'Egypt': 'Egypt → "Í-gíp-t" → Ai Cập 🇪🇬. Kim tự tháp 🏛️',
  'Vietnamese': 'Vietnam + ese → tiếng/người Việt',
  'English': 'England + ish → tiếng Anh. #1 ngôn ngữ toàn cầu',
  'Japanese': 'Japan + ese → tiếng Nhật',
  'Chinese': 'China + ese → tiếng Trung',
  'French': 'France + ch → tiếng Pháp',
  'Spanish': 'Spain + ish → tiếng Tây Ban Nha. #2 phổ biến nhất',
  'Korean': 'Korea + n → tiếng Hàn. K-pop, K-drama',
  'German': 'Germany → German → tiếng Đức',
  'Italian': 'Italy → Italian → tiếng Ý',
  'Thai': 'Thai → tiếng/người Thái 🇹🇭',
  'Foreign': 'Foreign → "pho-rần" → nước ngoài. Foreign language = ngoại ngữ',
  'Native': 'Native → "nây-típ" → bản xứ. Native speaker = người bản ngữ',
};

const CONTEXT_TIPS = {
  'Young': '💡 "Young" cho người, "new" cho vật. Young at heart = trẻ lòng',
  'Old': '💡 Dùng cho cả người và vật. How old are you? = Bạn bao nhiêu tuổi?',
  'Plump': '💡 Lịch sự hơn "fat" khi chỉ người. Thường dùng cho trẻ em/phụ nữ',
  'Clever': '💡 Clever nhấn mạnh sự nhanh trí, Smart nhấn mạnh kiến thức',
  'Curious': '💡 "Curious about" = tò mò về. "Curious" cũng = lạ, kỳ quặc',
  'Rude': '💡 Đối lập polite. "Don\'t be rude!" = Đừng thô lỗ!',
  'Loyal': '💡 Loyal to + người/tổ chức. A loyal friend = bạn trung thành',
  'Grateful': '💡 "Grateful for" = biết ơn về. I\'m grateful for your help',
  'Calm': '💡 "Stay calm" = giữ bình tĩnh. "Calm down" = trấn tĩnh lại',
  'Anxious': '💡 "Anxious about" = lo lắng. Anxiety disorder = rối loạn lo âu',

  'Apple': '💡 "Apple of my eye" = con cưng, người yêu quý. "An apple a day keeps the doctor away"',
  'Banana': '💡 "Go bananas" = phát điên! Banana split = kem chuối',
  'Watermelon': '💡 Không đếm được! "a piece/slice of watermelon"',
  'Lemon': '💡 "When life gives you lemons, make lemonade" = biến khó khăn thành cơ hội',
  'Coconut': '💡 Coconut oil = dầu dừa, rất phổ biến. Coconut milk = nước cốt dừa',
  'Durian': '💡 "King of fruits" nhưng bị cấm ở nhiều khách sạn vì mùi',
  'Avocado': '💡 "Avocado toast" = trend ẩm thực rất phổ biến ở phương Tây',
  'Potato': '💡 "Couch potato" = người lười (nằm sofa cả ngày). French fries',
  'Onion': '💡 "Layers of an onion" = nhiều lớp (ẩn dụ cho sự phức tạp)',
  'Mushroom': '💡 Cẩn thận: some mushrooms are poisonous (có nấm độc!)',

  'Breakfast': '💡 Gốc từ: break (phá) + fast (nhịn ăn). Bữa ăn phá vỡ nhịn ăn qua đêm',
  'Sandwich': '💡 Theo Earl of Sandwich (thế kỷ 18) - ông muốn ăn mà không bỏ chơi bài',
  'Dessert': '💡 Phân biệt: Dessert 🍰 (2 chữ S, tráng miệng) ≠ Desert 🏜️ (1 chữ S, sa mạc)',
  'Delicious': '💡 Formal hơn "yummy". Dùng trong mọi ngữ cảnh',
  'Raw': '💡 Raw food diet = ăn đồ sống. "Raw material" = nguyên liệu thô',
  'Spicy': '💡 Mức cay: mild → medium → hot → extra spicy',
  'Recipe': '💡 "Follow the recipe" = theo công thức. Family recipe = công thức gia truyền',

  'Espresso': '💡 Đậm nhất, base cho mọi loại cà phê. Double shot = 2 espresso',
  'Latte': '💡 Espresso + nhiều sữa. Ít đắng, phù hợp người mới uống cà phê',
  'Milk tea': '💡 Bubble tea/Boba = trà sữa trân châu. Rất hot ở châu Á!',
  'Smoothie': '💡 Healthy drink: trái cây xay + sữa/yogurt + ice',
  'Brew': '💡 "Brew coffee" = pha cà phê. "Let it brew" = để ngấm',
  'Straw': '💡 "Paper straw" = ống hút giấy (thay thế plastic straw). The last straw = giọt nước tràn ly',
  'Beverage': '💡 Formal: dùng trong menu nhà hàng. "Food and beverages"',

  'Wardrobe': '💡 "The Lion, the Witch and the Wardrobe" = Biên niên sử Narnia',
  'Refrigerator': '💡 Viết tắt "fridge" phổ biến hơn trong giao tiếp',
  'Air conditioner': '💡 Viết tắt: AC. "Turn on/off the AC" = bật/tắt máy lạnh',
  'Television': '💡 Viết tắt: TV. "Watch TV" không có "the": I watch TV every night',
  'Iron': '💡 Iron clothes = ủi quần áo. Iron cũng = sắt (Fe). Iron Man = Người Sắt',

  'Traffic jam': '💡 "Stuck in traffic" = bị kẹt xe. Rush hour = giờ cao điểm',
  'Commute': '💡 "My commute is 30 minutes" = đi làm mất 30 phút',
  'Roundabout': '💡 Ở Anh rất phổ biến, ở VN ít gặp hơn',

  'Crush': '💡 "I have a crush on..." = tôi thích thầm... (rất hay dùng)',
  'Propose': '💡 "He proposed to her" = anh ấy cầu hôn cô ấy. Get down on one knee',
  'Honeymoon': '💡 Thường đi du lịch ngay sau đám cưới',
  'Soulmate': '💡 "You are my soulmate" = em là tri kỷ/nửa kia của anh',

  'Half': '💡 "Half" phát âm /hæf/ - chữ L im lặng! Half price = nửa giá',
  'Dozen': '💡 "A dozen eggs" = một tá trứng (12). Baker\'s dozen = 13',
  'Percent': '💡 "50 percent" = 50%. "100 percent" = 100% = hoàn toàn',
  'Score': '💡 Final score = tỉ số cuối. Score a goal = ghi bàn',
  'Win': '💡 Win/Won/Won. Winner = người thắng. "Win-win" = đôi bên cùng có lợi',
  'Coach': '💡 Life coach = cố vấn cuộc sống. Coach cũng = xe buýt (Anh)',

  'Lunar New Year': '💡 Tết Nguyên Đán - lễ hội lớn nhất VN, TQ, Hàn',
  'Mid-Autumn': '💡 Mid-Autumn Festival: bánh trung thu, đèn lồng, ngắm trăng',
  'Festival': '💡 Music festival, food festival, film festival...',
  'Fireworks': '💡 "Watch fireworks" = xem pháo hoa. Firework show = màn bắn pháo hoa',
  'Tradition': '💡 "It\'s a tradition" = đó là truyền thống',

  'Goat': '💡 GOAT = Greatest Of All Time (hay nhất mọi thời đại). Slang rất phổ biến!',
  'Fox': '💡 "Sly as a fox" = tinh ranh như cáo',
  'Wolf': '💡 "A wolf in sheep\'s clothing" = sói đội lốt cừu',
  'Panda': '💡 Giant panda là quốc bảo Trung Quốc. WWF logo = panda',
  'Shark': '💡 Shark Tank (TV show). "Loan shark" = cho vay nặng lãi',
  'Bee': '💡 "Busy as a bee" = bận rộn. Spelling bee = cuộc thi đánh vần',
  'Spider': '💡 Spider-Man! "Spiderweb" = mạng nhện',

  'Thunder': '💡 Thunder (sấm = âm thanh) ≠ Lightning (chớp = ánh sáng)',
  'Rainbow': '💡 7 colors: Red, Orange, Yellow, Green, Blue, Indigo, Violet',
  'Volcano': '💡 Active volcano = núi lửa đang hoạt động. Eruption = phun trào',
  'Bamboo': '💡 Panda ăn bamboo! Bamboo grows very fast = tre mọc rất nhanh',
  'Rose': '💡 "A rose by any other name would smell as sweet" - Shakespeare',
  'Sunflower': '💡 Sunflower luôn hướng về mặt trời. Van Gogh\'s Sunflowers = tranh nổi tiếng',

  'Embassy': '💡 "Go to the embassy" khi cần visa hoặc hộ chiếu ở nước ngoài',
  'Supermarket': '💡 = grocery store (Mỹ). "Go to the supermarket" = đi siêu thị',
  'Zoo': '💡 "Take the kids to the zoo" = đưa con đi sở thú',

  'Singapore': '💡 Singa (sư tử) + pore (thành phố). "Quốc đảo sư tử"',
  'Canada': '💡 Biểu tượng: lá phong (maple leaf) 🍁. O Canada!',
  'Brazil': '💡 Nổi tiếng: bóng đá, Carnival, rừng Amazon',
  'Egypt': '💡 Pyramids (kim tự tháp) + Sphinx. Ancient civilization',
  'Native': '💡 "Native speaker" = người nói tiếng mẹ đẻ. "Native language" = tiếng mẹ đẻ',
  'Foreign': '💡 "Foreign country" = nước ngoài. "Foreigner" = người nước ngoài',
};

const RELATED_WORDS = {
  'Young': '↔️ old. ≈ youthful, juvenile. Họ: youngster, youth',
  'Old': '↔️ young/new. ≈ ancient, elderly. Họ: olden, old-fashioned',
  'Pale': '↔️ tan. ≈ light, fair-skinned',
  'Plump': '≈ chubby, round. ↔️ slim, thin',
  'Clever': '≈ smart, intelligent, bright. ↔️ foolish',
  'Curious': '≈ nosy, inquisitive. Họ: curiosity, curiously',
  'Rude': '≈ impolite, disrespectful. ↔️ polite, courteous',
  'Cruel': '≈ mean, harsh, brutal. ↔️ kind, gentle. Họ: cruelty',
  'Ambitious': '≈ driven, aspiring. Họ: ambition',
  'Loyal': '≈ faithful, devoted, dedicated. ↔️ disloyal, unfaithful',
  'Optimistic': '↔️ pessimistic. ≈ hopeful, positive',
  'Pessimistic': '↔️ optimistic. ≈ negative, gloomy',
  'Ashamed': '≈ embarrassed, humiliated. ↔️ proud',
  'Grateful': '≈ thankful, appreciative. ↔️ ungrateful. Họ: gratitude',
  'Calm': '≈ peaceful, relaxed, serene. ↔️ anxious, nervous',
  'Anxious': '≈ worried, nervous, uneasy. ↔️ calm, relaxed. Họ: anxiety',
  'Content': '≈ satisfied, pleased. ↔️ dissatisfied',

  'Apple': 'apple pie, apple juice, apple cider, apple sauce',
  'Banana': 'banana split, banana bread, banana peel',
  'Orange': 'orange juice (OJ), orange peel, blood orange',
  'Grape': 'grapefruit, grapevine, grape juice, raisin (nho khô)',
  'Mango': 'mango smoothie, mango sticky rice, dried mango',
  'Watermelon': 'watermelon seed, watermelon juice',
  'Strawberry': 'strawberry jam, strawberry cake, strawberry milkshake',
  'Coconut': 'coconut oil, coconut milk, coconut water, coconut cream',
  'Avocado': 'avocado toast, guacamole, avocado oil',
  'Lemon': 'lemonade, lemon juice, lemon zest, lemon tart',
  'Cherry': 'cherry blossom (hoa anh đào), cherry tomato, cherry pie',

  'Carrot': 'carrot cake, carrot stick, carrot juice',
  'Tomato': 'tomato sauce, tomato soup, cherry tomato, sun-dried tomato',
  'Potato': 'potato chip, mashed potato, baked potato, sweet potato',
  'Onion': 'onion ring, spring onion (hành lá), red onion',
  'Garlic': 'garlic bread, garlic sauce, garlic clove (tép tỏi)',
  'Cucumber': 'cucumber salad, pickle (dưa chuột muối)',
  'Corn': 'popcorn, cornflakes, corncob, corn syrup',
  'Mushroom': 'mushroom soup, mushroom sauce, shiitake mushroom',

  'Lamb': 'lamb chop, lamb leg, lamb stew',
  'Crab': 'crab meat, crab cake, crab stick',
  'Lobster': 'lobster tail, lobster bisque (súp tôm hùm)',
  'Salmon': 'smoked salmon, salmon sushi, salmon fillet',
  'Steak': 'rare/medium/well-done steak, steak house',

  'Cook': 'cooker, cooking, cookbook, well-cooked',
  'Boil': 'boiled, boiling, hard-boiled egg, soft-boiled egg',
  'Fry': 'fried, fryer, French fries, stir-fry, deep-fry',
  'Bake': 'baker, bakery, baked goods, half-baked',
  'Grill': 'grilled, grilling, BBQ grill',

  'Breakfast': 'brunch (breakfast + lunch), bed and breakfast (B&B)',
  'Sandwich': 'club sandwich, grilled cheese sandwich',
  'Pizza': 'pizza sauce, pizza dough, pepperoni pizza',
  'Burger': 'hamburger, cheeseburger, veggie burger',
  'Dessert': 'dessert menu, dessert spoon. ≠ desert (sa mạc)',

  'Sweet': '↔️ bitter/sour. Họ: sweetness, sweeten, sweetheart',
  'Sour': '↔️ sweet. Họ: sourness, sourdough',
  'Salty': 'salt, saltwater, saltiness. ↔️ bland',
  'Fresh': 'freshness, freshen, refresh, freshman',
  'Crispy': '≈ crunchy. Họ: crisp, crispness',
  'Soft': '↔️ hard. Họ: soften, software, softly',
  'Delicious': '≈ tasty, yummy, scrumptious, mouth-watering',

  'Espresso': 'double espresso, espresso shot, espresso machine',
  'Latte': 'café latte, matcha latte, vanilla latte',
  'Cappuccino': 'iced cappuccino, dry/wet cappuccino',
  'Smoothie': 'fruit smoothie, green smoothie, smoothie bowl',
  'Yogurt': 'Greek yogurt, frozen yogurt (froyo), yogurt parfait',
  'Cream': 'ice cream, cream cheese, whipped cream, sour cream',

  'Sofa': '≈ couch. Sofa bed = ghế sofa kiêm giường',
  'Wardrobe': '≈ closet (Mỹ). Walk-in wardrobe = phòng quần áo',
  'Desk': 'desktop, desk lamp, standing desk',
  'Shelf': 'shelves (pl.), bookshelf, shelf life',
  'Pillow': 'pillowcase, pillow fight, throw pillow',
  'Blanket': 'electric blanket, baby blanket, blanket statement',
  'Oven': 'microwave oven, oven mitt, Dutch oven',

  'Sweep': 'sweeper, swept (quá khứ), sweeping',
  'Wash': 'washer, washing, carwash, wash up',
  'Clean': 'cleaner, cleaning, cleanser. ↔️ dirty',

  'Road': 'roadside, road trip, crossroad, railroad',
  'Street': 'street food, street art, Wall Street, Main Street',
  'Highway': 'freeway (Mỹ), motorway (Anh), expressway',
  'Bridge': 'footbridge, drawbridge, bridge the gap',
  'Drive': 'driver, driveway, driving license, drive-through',

  'Crush': 'have a crush on, puppy love, infatuation',
  'Passion': 'passionate, compassion, passive',
  'Miss': 'missing, I miss you. Cũng = cô (Miss Smith)',
  'Heartbreak': 'heartbreaking, heartbroken, broken heart',
  'Faithful': '≈ loyal, devoted. ↔️ unfaithful. Họ: faith, faithfully',
  'Wedding': 'wedding ring, wedding dress, wedding cake, bridal',
  'Honeymoon': 'honeymoon phase, honeymoon destination',
  'Anniversary': 'wedding anniversary, work anniversary',

  'Half': 'halfway, half-time, half-price, halves (pl.)',
  'Double': 'double-check, double Dutch, body double',
  'Triple': 'triple play, triple crown, triple-check',
  'Add': 'addition, additional, add-on, address',
  'Multiply': 'multiplication, multiple, multiplier',
  'Divide': 'division, divided, divisor, dividend',
  'Equal': 'equality, equally, equalize, equation',
  'Percent': 'percentage, percentile',
  'Distance': 'distant, long-distance, distance learning',

  'Score': 'scoreboard, scorecard, high score. Cũng = 20 (tiếng cổ)',
  'Win': 'winner, winning, win-win. Win/Won/Won',
  'Lose': 'loser, losing, loss. Lose/Lost/Lost. ≠ Loose (lỏng)',
  'Jump': 'jumping, jumper, jump rope, high jump, long jump',
  'Medal': 'gold/silver/bronze medal, medalist',
  'Stadium': 'arena, colosseum, sport venue',

  'Holiday': 'on holiday, public holiday, holiday season',
  'Celebrate': 'celebration, celebrity, celebratory',
  'Decorate': 'decoration, decorator, decorative',
  'Fireworks': 'firecracker (pháo), sparkler (pháo sáng)',
  'Tradition': 'traditional, traditionally. ↔️ modern',
  'Surprise': 'surprising, surprisingly, surprise party',
  'Present': 'gift (đồng nghĩa), presentation, presenter',

  'Turtle': '≈ tortoise (rùa cạn). Sea turtle = rùa biển',
  'Wolf': 'wolves (pl.), werewolf (người sói), wolfpack',
  'Fox': 'foxy, foxhound, fox terrier. Arctic fox',
  'Giraffe': 'tallest animal, giraffe pattern',
  'Panda': 'giant panda, red panda, panda bear',
  'Eagle': 'bald eagle, eagle-eyed (tinh mắt)',
  'Penguin': 'emperor penguin, penguin colony',
  'Shark': 'great white shark, shark fin, shark attack',
  'Whale': 'blue whale, whale shark, humpback whale',
  'Dolphin': 'bottlenose dolphin, dolphin show',
  'Octopus': 'octopi/octopuses (pl.), tentacle (xúc tu)',
  'Bee': 'beekeeper, beehive, beeswax, honeybee',
  'Spider': 'spiderweb, spider silk, tarantula',

  'Sunny': 'sun, sunshine, sunburn, sunscreen',
  'Rainy': 'rain, rainfall, raincoat, rainstorm',
  'Thunder': 'thunderstorm, thunderbolt, thunderclap',
  'Lightning': 'lightning bolt, lightning rod, lightning fast',
  'Rainbow': '7 colors: red, orange, yellow, green, blue, indigo, violet',
  'Flood': 'flooding, floodgate, flooded, flash flood',
  'Drought': 'dry spell, water shortage',
  'Volcano': 'volcanic, eruption, lava, magma',
  'Valley': 'Silicon Valley, valley floor, river valley',
  'Cave': 'caveman, cave painting, cave exploration',
  'Leaf': 'leaves (pl.), leafy, leaf blower, tea leaf',
  'Branch': 'tree branch, branch office, branching',
  'Seed': 'seedling, sunflower seed, seed money',
  'Rose': 'rosebud, rosemary, rose garden, rose water',
  'Sunflower': 'sunflower seed, sunflower oil',
  'Bamboo': 'bamboo shoot, bamboo forest, bamboo mat',
  'Cactus': 'cacti (pl.), cactus flower, desert cactus',

  'Supermarket': '≈ grocery store (Mỹ). Hypermarket = đại siêu thị',
  'Café': 'café latte, internet café, sidewalk café',
  'Bakery': 'baker, bake, baked goods',
  'Zoo': 'zookeeper, zoology, zoologist',
  'Gym': 'gymnasium, gymnast, gymnastics',

  'Germany': 'German (người/ngôn ngữ), Berlin, Oktoberfest',
  'Italy': 'Italian, Rome, Venice, Milan, pizza, pasta',
  'Spain': 'Spanish, Madrid, Barcelona, flamenco',
  'Brazil': 'Brazilian, São Paulo, Rio, Amazon, samba',
  'Canada': 'Canadian, Ottawa, Toronto, maple syrup',
  'Vietnamese': 'Vietnam, Hanoi, Ho Chi Minh City, phở, áo dài',
  'English': 'England, British, American English, IELTS, TOEFL',
  'Japanese': 'Japan, Tokyo, anime, sushi, sakura',
  'Chinese': 'China, Beijing, Mandarin, dim sum, Great Wall',
  'Korean': 'Korea, Seoul, K-pop, kimchi, K-drama',
  'French': 'France, Paris, croissant, Eiffel Tower',
  'Spanish': 'Spain, Latin America, flamenco, paella',
  'Foreign': 'foreigner, foreign exchange, foreign policy',
  'Native': 'native speaker, native language, native plant',
};

// ── Main ──
const filePath = path.join(__dirname, '..', 'src', 'data', 'vocab-topics.js');
let content = fs.readFileSync(filePath, 'utf8');

let modified = 0;
let total = 0;

// Match words that DON'T already have memoryTip
// We need to match only entries without memoryTip
content = content.replace(
  /\{\s*word:\s*'([^']+)',\s*phonetic:\s*'([^']*)',\s*meaning:\s*'([^']*)',\s*example:\s*'([^']*)',\s*illustration:\s*'([^']*)'\s*\}/g,
  (match, word, phonetic, meaning, example, illustration) => {
    // Skip if already has memoryTip (would have been caught by different regex)
    total++;
    const tip = MEMORY_TIPS[word];
    const ctx = CONTEXT_TIPS[word];
    const rel = RELATED_WORDS[word];

    if (tip || ctx || rel) {
      modified++;
      let result = `{ word: '${word}', phonetic: '${phonetic}', meaning: '${meaning}', example: '${example}', illustration: '${illustration}'`;
      if (tip) result += `, memoryTip: '${tip.replace(/'/g, "\\'")}'`;
      if (ctx) result += `, context: '${ctx.replace(/'/g, "\\'")}'`;
      if (rel) result += `, related: '${rel.replace(/'/g, "\\'")}'`;
      result += ' }';
      return result;
    }
    return match;
  }
);

fs.writeFileSync(filePath, content, 'utf8');
console.log(`Done! ${modified} more words enhanced (out of ${total} remaining without tips).`);
